# Generated by Django 4.0 on 2022-03-24 20:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
